---
- hosts: myhosts
  tasks:
  - name: create multiple files
    file:
      path: '{{ item.location }}'
      state: touch
      mode: '{{ item.mode }}'
      owner: '{{ item.owner }}'
      group: '{{ item.group }}'
    with_items:
    - { location: '/tmp/file8' mode: '0666' owner: 'shubham' group: 'shubham'}
    - { location: '/tmp/file9' mode: '0444' owner: 'centos' group: 'centos'}
